project:
  type: website
  output-dir: docs

website:
  title: "Richard Montes Lemus"
  favicon: images/logo.jpg
  navbar:
    logo: images/logo.jpg
    logo-alt: the name richie montes lemus with a logo
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      # - href: resources.qmd
        # text: Resources
      # - icon: github
        # href: https://github.com/richardmonteslemus
  page-footer:
        left: Copyright 2025, Richie Montes Lemus

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
    mainfont: Nunito
    



